### PR TITLE
Accept Multiple video Resolutions and Canvas Recording

### LINKED ISSUE #418: GSoC Infragram.org full-screen UI and video upload Discussion and Planning
Hi, everyone! This is the Planning Issue for the [Infragram.org: full-screen UI and video upload](https://summerofcode.withgoogle.com/programs/2022/projects/rP8hthBg) for [infragram.org](https://infragram.org/). The project is in collaboration with the [Outreachy proposal: Design a new full-screen user interface for Infragram.org](https://publiclab.org/notes/stefq1111/04-08-2022/outreachy-proposal) . All are open for discussion and improvement.

**Process Video Locally**
- [x] Allow conversion of entire video.
- [x] Implement video controls on canvas.
- [x] Include another Canvas Element ( second Canvas ).
- [x] Record  video on process at second canvas.
- [x]  Save processed video file.
- [x] Integrate the above functionalities to with UI of outreachy collaborator. @stephaniequintana 

**Allow selecting multiple output resolutions as well**
- [x] Dynamically change the size of second canvas to fit required resolution.
- [x] Integrate the above functionalities to with UI of outreachy collaborator.

**Integrate Teamsys latest camera selection API** 
 Issue #39
- [ ] Download Temasys/AdapterJS library.
- [ ] Change all instances of the word `webRtcOptions.context ` to `webRtcDetectedType`
- [ ] Remove code `if (webRtcOptions.context === "flash")`
[Reference 1](https://github.com/publiclab/spectral-workbench.js/pull/172)  [Reference 2]( https://github.com/publiclab/spectral-workbench.js/issues/87)

**Accept multiple webcam resolutions**
- [x] Maintain css canvas size.
- [x] Change HTML canvas size to fit requested resolution.
- [x] Integrate the above functionalities to with UI of outreachy collaborator.

**Write UI tests for new Infragram UI Jest** 
- [ ] write test for infragram UI functionalities.

**Allow zooming/panning of video**
- [x]  Zooming :  Add uScale of uniform vect2 to shader.frag and shader.vert. 
- [ ]  Panning :  Add uPan of uniform vect2 to shader.frag and shader.vert .
- [ ] Implement above functionalities to infragram drawscreen function.
- [ ] Integrate the above functionalities to with UI of outreachy collaborator.

**Miscellaneous**

- [ ]  Add option to close webcam input
- [ ]  Enable image and video stream mirroring
- [x]  Add file filters on input to optimize infrared analysis

### PR DESCRIPTION
**Pull request by Forchapeatl**
**Accept Multiple video Resolutions and Canvas Recording** 

https://user-images.githubusercontent.com/24577149/175521082-5565a39b-3180-4321-8c5a-5a811797cc1a.mp4

Hello @jywarren @TildaDares @cesswairimu and @stephaniequintana 
I have
- [x] Included logic to accept multiple video resolutions.
- [x] Included logic to record and download  canvas.
on [https://forchapeatl.github.io/infragram/index2.html](https://forchapeatl.github.io/infragram/index2.html)

**Questions**
1. The flow to update web resolution is
       **CASE A**
     a. Turn on Camera.
     b. Select resolution. 
 or  
       **CASE B**
    a. Select resolution,.
    b. Turn on Camera.
The problem is on case B our presets modal will show after every resolution is selected. I propose keep the multiple resolution button disabled until our camera is turned on.

**Optimization**

The frames move much slower at higher resolutions.The resolution limit is subject to to the RAM of the computer.  I will have to set a maximum resolution limit for each device. [reference](https://webrtc.github.io/samples/src/content/getusermedia/resolution/)  

Fixes #418 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature 

branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Forchapeatl** [comment]
@cesswairimu thank you for the kind remarks. I will discuss with @stephaniequintana on the styling

**Comment by stephaniequintana** [comment]
Great job, @Forchapeatl!! You're really truckin' along, I love it!! Congrats on this:exclamation: :star2: :boom:  :dizzy:

**Comment by jywarren** [comment]
@Forchapeatl this is really cool! I agree with Cess that path A sounds good - i think it's OK to force people into that flow and it doesn't seem like it will prevent people from doing anything. Better to keep it simple by design!

I am wondering how we should best organize the UI here. I have a few questions - first, can we visually isolate/contain the new controls from other controls AND from each other, to simplify the view for the user, and second, in the code itself so that when the time comes, @stephaniequintana knows exactly what new code needs to be copied into the new UI? 

@stephaniequintana do you have ideas on how to do this? I was thinking maybe we could... make them appear only when you click the video button... and make the record button appear as a button in the same row (and same style) as the camera button? Could we make the webcam/video/upload buttons disappear and replace them with the new controls like resolution and record? Could the record button be red? These are just a few ideas.

Hm, are we missing a commit here, though? I don't see the extra new HTML for the buttons the way I see in https://forchapeatl.github.io/infragram/index2.html - just wondering if we missed something.

I just want to say again this is really exciting, and great work!

**Comment by Forchapeatl** [comment]
Hello @stephaniequintana sorry for the delay. I have updated the commits with both the dist/infragram.js and index.ntml files.
I will incorporate the newUI at my end too (under this PR). I think the resolution and record buttons should be different. Let's show the record button when Webrtc return true. I will attach my functionality to the newUI. so that we can be in sync. Thank you.

**Comment by jywarren** [comment]
> if the button is pressed by mistake or out of curiosity then the page may need to be reloaded in order to switch back to camera/image-upload (?) - I'll play around with both, disappearing the camera/webcam buttons and making room on the same row to the right of the video icon.

Good question. I think needing to reload the site isn't the worst, especially in the v1 interface. On the other hand, in v2, the process might work differently to avoid this, or we could imagine having an `x` button to close this new little pane. I trust you two to think through the flow and figure something out. You might also ask other Outreachy/GSoC fellows to try it and see what seems natural or confusing to them!

> Does the resolution selection and record buttons need to be separate buttons? - Just curious. We might say "Begin recording in:" resButton1, resButton2... and have them turn red once hovered over? Just a thought...

I think this sounds promising, but might also do well with testing -- especially in mobile where there is no hover effect (touchscreen). Haha someday we'll be able to detect a hover-finger-above-screen... but not yet.

**Pull request closed without merging**
