### PR TITLE
added FTO issue template for bot

### PR DESCRIPTION
**Pull request by shubhangi013**
WRT the discussion at https://github.com/publiclab/infragram/issues/318#issuecomment-1089250561, I added the issue template, renamed and edited it to make it compatible for the bot.

### CODE REVIEW

**Comment by shubhangi013** [comment]
> Hi @shubhangi013, the template needs to be in the directory `.github/ISSUE_TEMPLATE`.

Yep, I created the directory and added the template there.

**Comment by TildaDares** [comment]
Oh sorry, my bad!

**Review by TildaDares — APPROVED** [review]
Thanks @shubhangi013. Great work!!

**Comment by shubhangi013** [comment]
> Thanks @shubhangi013. Great work!!

Thankyou so much 😊 ♥️

**Pull request merged**
