### PR TITLE
added favicon and put the qna in a panel

### LINKED ISSUE #197: Q&A are  clustered
QnA should be in a panel for ease of the user.

### PR DESCRIPTION
**Pull request by shubhangi013**
Signed-off-by: shubhangi013 <choudharyshubhangi13@gmail.com>

Fixes #197 
Here is the proof that the changes work fine.
Screenshot from 2022-03-02 22-11-01

### CODE REVIEW

**Comment by Syed-Ansar** [comment]
Hey @shubhangi013 disable your editors linter/formatter then commit your changes.

**Comment by shubhangi013** [comment]
> Hey @shubhangi013 disable your editors linter/formatter then commit your changes.

should I increase/decrease the tab size from 2 spaces to 3 spaces?

**Comment by Syed-Ansar** [comment]
> > Hey @shubhangi013 disable your editors linter/formatter then commit your changes.
> 
> should I increase the tab size from 2 spaces to 3 spaces?

No it is not about Tab spaces.If linters/formatters like prettier in editors are active then they will format the whole code. so to maintain the format of repo we have to disable the linters/formatters in editors.

**Comment by shubhangi013** [comment]
@Syed-Ansar I disabled prettier and the linter and committed the changes.

**Comment by TildaDares** [comment]
Hi @shubhangi013, you might have to undo all the changes you made by pasting a copy of the files from this remote repo to your local version. For example, since you changed `index.html`, you'll copy the content of this file https://github.com/publiclab/infragram/blob/main/index.html and paste it into the `index.html` file in your local environment. That'll undo all the changes and then you can add whatever change you want. I hope that helps.

**Comment by TildaDares** [comment]
Also, I think it's better if we solve only one issue in a PR. Since there's already an issue open for the missing favicon, you can focus on the qna panel. Can you open a separate issue for the qna panel issue so that we can close the favicon issue since it's a duplicate of #193. Thank you!

**Comment by shubhangi013** [comment]
> Also, I think it's better if we solve only one issue in a PR. Since there's already an issue open for the missing favicon, you can focus on the qna panel. Can you open a separate issue for the qna panel issue so that we can close the favicon issue since it's a duplicate of #193. Thank you!

My bad. I might've missed this one issue. :sweat_smile: I'll open a new issue and do the changes from scratch. Thank you!

**Comment by shubhangi013** [comment]
@TildaDares I've edited my previous issue for just the QnA panel. should I close this PR and open a new one?

**Comment by TildaDares** [comment]
@shubhangi013 it's upto you. If you think you can't make the required changes to this PR, then feel free to open a new pR.

**Comment by shubhangi013** [comment]
> @shubhangi013 it's up to you. If you think you can't make the required changes to this PR, then feel free to open a new PR.

I'll open a fresh one. I'll have to checkout to a new branch.

**Pull request closed without merging**
