### PR TITLE
Missing semi-colon in infragram.css

### PR DESCRIPTION
**Pull request by marshatiisa**
@TildaDares @jywarren I tried to make this a first-timers issue but there was no branch option at the bottom. Can you guide me on this?

### CODE REVIEW

**Comment by TildaDares** [comment]
@marshatiisa I don’t understand what branch option means.

**Comment by marshatiisa** [comment]
Screen Shot 2022-04-12 at 14 20 12
Screen Shot 2022-04-12 at 14 20 27
The first screenshot shows what i see and the second is from the first timers bot tutorial

**Comment by TildaDares** [comment]
@marshatiisa I’m not sure why the branch option isn’t showing on your end because it’s working on mine.

**Comment by marshatiisa** [comment]
Okay then. Could you review the change and merge if thats okay

**Review by TildaDares — APPROVED** [review]
Thanks @marshatiisa

**Pull request merged**
