### PR TITLE
Added information for contribution

### LINKED ISSUE #40: Add more information in the Readme to make contributions easy
Currently. readme contains only little information which makes it difficult to new contributors to get clarrity of the project. 

Inspiration for Readme can be taken from - https://github.com/publiclab/plots2/blob/master/README.md

Any help will be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by debck**
Fixes #40 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation

Thanks!

### CODE REVIEW

**Comment by debck** [comment]
@publiclab/reviewers please review this PR

**Comment by IshaGupta18** [comment]
I think this is good to go @debck!

**Comment by CoderJolly** [comment]
> @publiclab/reviewers please review this PR

All tests passed, Its cool @debck

**Comment by ananyaarun** [comment]
Hey @debck , Maybe we can add more specific details on contributing to the infragram project.
Like local installation etc.
This looks like an old issue to me and so are the others in this repo.
It would be nice to make readme more newcomer friendly by added more instructions :)

**Comment by jywarren** [comment]
This is really nice, thank you! I like @ananyaarun's suggestions too if you'd like to do a follow-up! Thanks everyone for the reviews!

Also, if you'd like to point at the specific repository there is a dropdown for that in code.publiclab.org, that changes the URL. Thanks!!!

**Pull request merged**
