### PR TITLE
Fixed typos in .github/config.yml

### PR DESCRIPTION
**Pull request by Somya-Singhal**
Found a small typo in  .github/config.yml

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
Thank you @Somya-Singhal!!

**Comment by TildaDares** [comment]
Congratulations🎉

**Comment by Somya-Singhal** [comment]
Thank you @TildaDares , I am really excited to work on this project could you also guide me what could be my next steps, so that I could help this community in the best possible way.

**Comment by TildaDares** [comment]
@Somya-Singhal You can look out for issues with the `help-wanted` tag in both [Infragram](https://github.com/publiclab/infragram/labels/help%20wanted) and [plots2](https://github.com/publiclab/plots2/labels/help%20wanted).

**Pull request merged**
