### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Simplecodez**
Removing <p></p> from line 144

Fixes #0000 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Simplecodez** [comment]
I just worked on this now

**Comment by Simplecodez** [comment]
https://github.com/publiclab/infragram/pull/475/commits/bf628d8fa98c92c37eba7beae5b1f73172b24b46

**Comment by Simplecodez** [comment]
Please how do I get one to work on?

**Comment by TildaDares** [comment]
Resolved in #477

**Pull request closed without merging**
