### PR TITLE
Start test Server

### PR DESCRIPTION
**Pull request by Forchapeatl**
Added code to start test server

Fixes #449 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by Forchapeatl** [comment]
Hello @jywarren It seems when our server is running. We can't perform any other action. We must stop the server for the test to proceed. Hence I propose we test on Public Url of Infragram.

**Comment by jywarren** [comment]
Can you try "http-server &&" ? That will fork the process and let you keep
running commands.

**Comment by jywarren** [comment]
Or maybe it's "http-server &" ?

**Comment by Forchapeatl** [comment]
Thank you @jywarren . I wll close this PR  and include the changes [Jest configurations](https://github.com/publiclab/infragram/pull/449)

**Pull request closed without merging**
