### PR TITLE
Change ANALYZE to CONVERT/ANALYZE in help text

### PR DESCRIPTION
**Pull request by alicendeh**
Solution to issue 224 assigned to me - https://github.com/publiclab/infragram/issues/224

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
Thanks @alicendeh for working on this!

**Comment by TildaDares** [comment]
Welcome to Public Lab @alicendeh 🎉

**Comment by alicendeh** [comment]
Thank you☺️

**Comment by mehul89** [comment]
THANK YOU VERY MUCH FOR THE MERGED THIS ISSUE @TildaDares  🙂

**Pull request merged**
