### PR TITLE
Create ci.yml for github actions (renamed tests.yml) (#156)

### PR DESCRIPTION
**Pull request by jywarren**
* Create ci.yml

This commit is to migrate checks from TravisCI to GitHub Actions

* Update ci.yml

* Update and rename ci.yml to tests.yml

* Update tests.yml

* Update tests.yml

* Update tests.yml

* Update tests.yml

* Update tests.yml

Co-authored-by: Govind Goel <52847415+govindgoel@users.noreply.github.com>

### CODE REVIEW

**Comment by jywarren** [comment]
@govindgoel -- got it to work! Whew!!! Yikes this was a tough one to crack!

**Comment by jywarren** [comment]
This looks great, but: 

```
0s
Run npm test

> infragram@0.3.0 test /home/runner/work/infragram/infragram
> echo 'Error: no test specified'

Error: no test specified
```

**Comment by jywarren** [comment]
Hmm, indeed that'd be cool, are you interested in it? However it could be
quite hard to code them for webgl, it'd have to be kind of like the tests
in Image Sequencer!

**Comment by govindgoel** [comment]
I have to look at it but I can give it a try though 😅

**Pull request merged**
