### PR TITLE
Toggle overlay controls on only when using grid overlay 

### PR DESCRIPTION
**Pull request by select-case**

### CODE REVIEW

**Comment by select-case** [comment]
Please review

Toggle overlay controls on only when using grid overlay #179

**Review by jywarren — CHANGES_REQUESTED** [review]

**Comment by jywarren** [comment]
Also, I'm curious, are you interested in the GSoC or Outreachy programs?

**Comment by select-case** [comment]
> Also, I'm curious, are you interested in the GSoC or Outreachy programs?

Yes. I am just starting out and don't really know how to go about GSoC yet.

**Review by TildaDares — APPROVED** [review]
Great work @select-case. Thank you!

**Comment by jywarren** [comment]
Ah whoops I believe @TildaDares was saying to leave this one open and close the others? Or is #183 the preferred one to review and merge? Thank you!

**Comment by jywarren** [comment]
Looks super. Thank you!!!

**Pull request merged**
