### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sonaljain067**
I have made corrections in spelling and grammar.

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
These are really great changes. Thank you!!

**Comment by sonaljain067** [comment]
Thanks for reviewing!

**Comment by sonaljain067** [comment]
Hey, do I need to create issue for the same?

**Comment by TildaDares** [comment]
Hi @sonaljain067, this is fine.

**Comment by sonaljain067** [comment]
Okay!

**Review by govindgoel — APPROVED** [review]

**Comment by sonaljain067** [comment]
> Congratulations @sonaljain067 🎉

Thanks a lot!

**Pull request merged**
