### PR TITLE
Added Sample Images to Output Section

### PR DESCRIPTION
**Pull request by stephaniequintana**
Updated README.md to include sample images.

Screen Shot 2022-06-15 at 4 42 14 AM

Fixes #0000 
No issue was created for this PR.
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Review by jywarren — APPROVED** [review]
Looks good - would you like to try merging this, partially just to confirm that you have permissions to do so? I'd still like to be sure we get approvals as a matter of workflow policy, but it's good to confirm that you technically have the permission to do a merge. Thanks!

**Comment by stephaniequintana** [comment]
I would like to, but I'm not see an option to do so. I am getting a message that "Only those with write access to this repository can merge.."

**Comment by jywarren** [comment]
Hi, i'm sorry i tried responding but it didn't go through. I have updated permissions on this project, would you mind trying again? Thank you!

**Comment by jywarren** [comment]
Oh ok... I adjusted the privileges... Can you now? Thanks!!

**Pull request merged**
