### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by stephaniequintana**
This is the working draft of the new interface for the sandbox page of infragram.org.
It is the first PR to be implemented from the Infragram - Full-Screen User Interface project #0415 (Planning and Discussion).
Functionality will be added and the UI will be updated as necessary in upcoming PRs.

This PR replaces #0417, the code has been updated:
- added infragram2.css
- fixed many responsive issues and cleaned up code (comments, un-used selectors...)

Screen Shot 2022-06-21 at 1 30 24 PM

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by stephaniequintana** [comment]
@jywarren, @TildaDares, @cesswairimu 

This is the draft UI that we will use to build upon. All feedback, opinions and suggestions are greatly appreciated. At this point, I do not feel like there is a visual hierarchy to this new UI, but perhaps once we add in steps we can achieve this.

Please let me know if you would like any specific changes before moving forward.

**Comment by stephaniequintana** [comment]
Great, I'm glad you made sense of it for me. I'm on the road right now, but will be able to take a closer look at it this afternoon. Thanks, @jywarren

**Comment by jywarren** [comment]
So what I found was that in GitPod, I tried checking out the main branch `git checkout main`, then I ran `git pull origin main`, but it said it pulled from `stephaniequintana/infragram`, not `publiclab/infragram` -- and when I checked recent commits with `git log` it showed those separate commits that hadn't been squashed:

```
commit f804c26bcfca34613c5bb45d0a3647a4eaf41811 (HEAD -> main, origin/main, origin/HEAD)
Author: Stephanie Quintana <81270711+stephaniequintana@users.noreply.github.com>
Date:   Thu Jun 16 08:45:36 2022 -0500

    Update README.md
    
    Great addition, @jywarren - this'll come in handy when including them as samples on the sandbox page, too.

commit cc0868c6dda2fe063197f881db957e9df826f915
Author: Stephanie Quintana <81270711+stephaniequintana@users.noreply.github.com>
Date:   Wed Jun 15 04:38:45 2022 -0500

    Update README.md
``` 

So what I really want to do is rewind the main branch to get back in sync with the `publiclab/infragram` main branch. First, I look back in `git log` results to find the last commit that was also on the `publiclab/infragram` main branch -- before it went out of sync. I think that's:

```
commit 13fcd4539f0c40a3366b4884a18ccbcf0ab8124a
Merge: 6094993 ceab311
Author: Tilda Udufo <mathildaudufo@gmail.com>
Date:   Thu Mar 31 17:10:28 2022 +0100

    Merge pull request #290 from daluclemas/patch-2
    
    updated config.yml file as requested in issue #284
```

I can rewind to that commit with `git reset --hard 13fcd4539f0c40a3366b4884a18ccbcf0ab8124a` -- a slightly risky command because it discards later commits. But I'm double checking (with `git status`) that I'm running this on the main branch -- your features in the `new-ui` branch is still safe. 

When i run the `reset` I then run `git pull https://github.com/publiclab/infragram.git main` to fetch the latest commits from the `publiclab/infragram` main branch, so my local is completely in sync with the `publiclab/infragram` remote. We can check `git log`, where i see the last commit is from #419 -- all good! Now I can `git checkout new-ui` and try rebasing again over the latest synced main branch. 

And although it's not completely smooth -- i still had to resolve the conflicts in the README manually -- a bit annoying, took a few steps. Maybe I could've run the "skip" command on some of these. But we'll be able to see if any of the README changes went wrong when I open a new PR.

Now it's rebased:

```
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: could not apply 5f19b08... Update README.md
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 5f19b08... Update README.md
gitpod /workspace/infragram (new-ui|REBASE 1/10) $ vi README.md 
gitpod /workspace/infragram (new-ui|REBASE 1/10) $ git add README.md 
gitpod /workspace/infragram (new-ui|REBASE 1/10) $ git rebase --continue
```

OK -- so, looks like it worked but a couple commits somehow persisted in the middle -- i'll try redoing the rebase skipping these. 

```
Added link of tutorial for creating a PULL REQUEST f53ab45
Bump minimist from 1.2.5 to 1.2.6 (publiclab#346)  ddf9819
```

OK -- that worked -- i just added "drop" to the commits that weren't relevant, during an interactive rebase `git rebase -i main`. 

OK sooooo -- that PR looks great: https://github.com/publiclab/infragram/pull/426

Now -- how do we avoid this again? Here's the clue -- #419 says: `jywarren merged 3 commits into publiclab:main from stephaniequintana:main` -- that means, that PR had been made from your local main branch, and you had pushed it up to your remote main branch on the `stephaniequintana/infragram` fork. That means you were then doing work on top of an out-of-sync main branch -- it had the #419 commits on it. 

That's a pretty common issue, it happens to folks all the time. You just have to remember to be opening new PRs from a named feature branch and not your main branch. AND you need to occasionally go into your local main branch and `git pull https://github.com/publiclab/infragram.git main` to be sure it's up to date. That said, usually as long as your local main branch doesn't have any commits that the root fork (publiclab/infragram), GitHub will just figure it out and you don't need to keep updating your local main. 

Sorry for such a long comment, but I hope walking through each step makes sense! Please let me know if there are things you didn't get here and we can dig into it a bit more. I'm going to merge #426 now!

**Comment by jywarren** [comment]
No worries at all, I'm glad it makes sense! Sounds good and looking forward
to what comes next!!

**Pull request closed without merging**
