### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ishumi007**
Changes made :
image

### CODE REVIEW

**Comment by ishumi007** [comment]
closes #234

**Review by pydevsg — APPROVED** [review]

**Comment by pydevsg** [comment]
Good start @ishumi007 🎉

**Comment by ishumi007** [comment]
> Good start @ishumi007 🎉

thanks a lot @pydevsg for reviewing.

**Review by TildaDares — APPROVED** [review]
Thanks @ishumi007. This looks great!

Thanks @pydevsg for reviewing.

**Pull request merged**
