### PR TITLE
Grid overlay button style changed from primary to default

### PR DESCRIPTION
**Pull request by Kemifrank**
I have successfully changed the grid overlay button style from primary to default.

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @Kemifrank, can you add the issue number in the format `Fixes #0000`? Thanks!

**Comment by Kemifrank** [comment]
Issue number #260

**Review by TildaDares — APPROVED** [review]
Thanks @Kemifrank!!

**Comment by TildaDares** [comment]
Congratulations @Kemifrank 🎉

**Pull request merged**
