### PR TITLE
Create ci.yml for github actions

### PR DESCRIPTION
**Pull request by govindgoel**
This commit is to migrate checks from TravisCI to GitHub Actions.

### CODE REVIEW

**Comment by govindgoel** [comment]
> Test run on forked repo
Screenshot 2021-05-23 at 3 42 20 AM

**Comment by govindgoel** [comment]
@jywarren Can you review this

**Comment by jywarren** [comment]
Hmm. i thought if I opened the PR my privileges would get it to run. But i can't seem to.

I also checked https://github.community/t/workflow-does-not-start/17618/8 -- any other ideas? Thanks so much for trying this!

**Comment by jywarren** [comment]
Got it working in https://github.com/publiclab/infragram/pull/157 !!

**Pull request closed without merging**
