### PR TITLE
add toggleable grid overlay button #14

### PR DESCRIPTION
**Pull request by mrtmrtmlck**
Toggleable grid overlay button added.

### CODE REVIEW

**Comment by mrtmrtmlck** [comment]
@jywarren It should work now. Thank you :blush:

**Comment by jywarren** [comment]
This looks great! Would you be interested in doing some follow-up tasks related to this? Some of these, perhaps?

https://github.com/publiclab/infragram/issues/14#issuecomment-437121001

**Comment by jywarren** [comment]
Thanks so much!!!

**Comment by mrtmrtmlck** [comment]
> This looks great! Would you be interested in doing some follow-up tasks related to this? Some of these, perhaps?
> 
> [#14 (comment)](https://github.com/publiclab/infragram/issues/14#issuecomment-437121001)

Sure, a pleasure for me 😊

**Pull request merged**
