### PR TITLE
Hide grid overlay controls on initial display 

### PR DESCRIPTION
**Pull request by Hydriah**
fixes#000 index.html @line151

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
Thanks @Hydriah!! Great work

**Comment by TildaDares** [comment]
Congratulations @Hydriah 🎉

**Comment by Hydriah** [comment]
thanks @TildaDares  its great to be in this community

**Comment by Hydriah** [comment]
thanks @TildaDares  its great to be in this community

**Pull request merged**
